# Generated by apps2asm.py

.section .zdata

.set kNumberOfApps, 3

kPongTitle: .word 0xAA7A8403, 0x1105F82D, 0x00022A6A
kMipsInvaderTitle: .word 0xBAB90E03, 0x1CC69281, 0x0002D81F
kSquaresTitle: .word 0x06E80503, 0x20B6D71E, 0x0000002E

kAppTexts: .word kSquaresTitle, kMipsInvaderTitle, kPongTitle
kAppEntries: .word __pong_main, __mips_invader_main, __squares_main
