# Generated by apps2asm.py

.section .zdata

.set kNumberOfApps, 3

kFlapsTheMipsTitle: .word 0x28331304, 0x21013A37, 0x1A012C2F, 0x00201D16
kPongTitle: .word 0x1B1C1D04, 0x352C0114, 0x3C362A01, 0x393C2C33
kMipsInvaderTitle: .word 0x37301A04, 0x3516013A, 0x2C2B283D, 0x00000039

kAppTexts: .word kMipsInvaderTitle, kPongTitle, kFlapsTheMipsTitle
kAppEntries: .word __flaps_the_mips_main, __pong_main, __mips_invader_main, __screen_saver_main, blue_screen, about_page
