#!/usr/bin/python3
"""

Main script for generating the apps in the home menu.

Copyright (C) 2018, Guillaume Gonnet
License MIT

"""

import os.path as path
import sys
import argparse


# Push 'apps' folder for loading 'genapps'
folder = path.join(path.dirname(__file__), 'apps')
sys.path.append(path.abspath(folder))

from genapps import genapps


def main():
    "Entry point of the application."

    parser = argparse.ArgumentParser(prog="makeapps",
        description="Main script for generating the apps in the home menu.")

    args = parser.parse_args()

    here = path.dirname(__file__)
    genapps(path.abspath(path.join(here, "../apps")))


if __name__ == "__main__":
    main()
