#!/usr/bin/python3
"""

Convert the app list into an ASM file.

Copyright (C) 2018, Guillaume Gonnet
License MIT

"""

import os.path as path
import sys
import argparse
import configparser
import re


# Push 'text' folder for loading 'text2asm'
folder = path.join(path.dirname(__file__), '..', 'text')
sys.path.append(path.abspath(folder))

from text2asm import convert_text


def read_ini(filename):
    "Read an INI file."

    config = configparser.ConfigParser()
    with open(filename) as file:
        config.read_string("[DEFAULT]\n%s" % file.read())

    return config["DEFAULT"]



def convert_app(out, infolder, name):
    "Convert a single app to ASM code."

    # varname = name.
    config = read_ini("%s/%s.ini" % (infolder, name))

    assert "directory" in config, "Please provide 'directory' in %s.ini" % name
    assert "title" in config, "Please provide 'title' in %s.ini" % name

    data = convert_text(config.get("title").strip())



def apps2asm(infolder, outname):
    "Convert the app list into an ASM file."

    out = open(outname, "w")
    out.write("# Generated by apps2asm.py\n\n")
    out.write(".data\n\n")

    assert path.isfile(infolder + "/#all-apps.ini"), "File #all-apps.ini is missing"
    config = read_ini(infolder + "/#all-apps.ini")

    apps = re.findall("^\s*-\s*(.*)$", config.get("apps").strip(), re.M)
    out.write(".set kNumberOfApps, %d\n" % len(apps))

    texts = []
    for name in apps:
        texts.append(convert_app(out, infolder, name))

    out.write("kAppTexts: .word %s\n" % ", ".join(texts))
    out.close()



def main():
    "Entry point of the application."

    parser = argparse.ArgumentParser(prog="apps2asm",
        description="Convert the app list into an ASM file.")

    parser.add_argument("folder", default="apps", nargs="?",
        help="folder containing the apps, from root (default=apps)")

    args = parser.parse_args()
    apps2asm("../../" + args.folder, "../../src/menu/apps-data.s")


if __name__ == "__main__":
    main()
